version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"

python:
    install:
    - requirements: doc/readthedocs/requirements.txt

sphinx:
    configuration: doc/readthedocs/conf.py
